# Generated by Django 3.2.4 on 2021-08-02 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='parent',
            new_name='team_leader',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
