# Generated by Django 3.2.4 on 2021-08-03 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210802_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='team_leader',
            new_name='team_member',
        ),
    ]
