# Generated by Django 3.2.4 on 2021-08-04 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_team_leader_user_team_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='team_member',
            new_name='parent',
        ),
    ]
