# Generated by Django 3.2.5 on 2021-08-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievements',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='hobbies',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='worksamples',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='achievements',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
