# Generated by Django 3.2.5 on 2021-08-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20210813_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='hobbies',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='worksamples',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='certificate',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='education',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hobbies',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='language',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='worksamples',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
