# Generated by Django 3.2.5 on 2021-08-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20210731_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeuserdetails',
            name='photo',
            field=models.ImageField(blank=True, default='../static/images/default_avatar.png', upload_to=''),
        ),
    ]
